Activity Diagram

@startuml configuration

    scale 1

    start
        :Open ATUM Configuration Tool;
        :Checkout "Configuration_Files" for EcoSystem Updating;
        :Modify "Configuration_Files";
        while (Modifying Configuration_Files) is (is Modifying)
        :Change Parameters for Product and Connectivity;
        endwhile (Is Modified)
        :CheckIn Configuration_Files for Product and Connectivity;
        :Export Configuration_Files;
        fork
        :Product Configuration;
        fork again
        :IoT Configuration;
        end fork
        :Install on Appliance Product Config;
        :Install on Cloud IoT Config;
    stop

@enduml