Activity Diagram

@startuml Config

    scale 1

    start
        :Open Configuration Tool;
        :Checkout Settings_File;
        :Modify Settings_File;
        while (Modifying Settings_File) is (is Modifying)
        :Change Parameters;
        endwhile (Is Modified)
        fork
        :Mail invoice;
        fork again
        :Load games;
        end fork
        :Install and play;
    stop

@enduml