@startuml programming


    autonumber
    actor HMI_SW_Developer
    actor MC_SW_Developer
    actor Systems_Engineer
    actor RTE

    ==Discrete Release SW==

    HMI_SW_Developer -[#blue]>  SW_Check_In: Compile/Check In SW for HMI
    MC_SW_Developer -[#blue]>  SW_Check_In: Compile/Check In SW for Main Control
    Systems_Engineer -[#blue]>  SW_Check_In: Compile/Check In Configurations
    Systems_Engineer -[#blue]>  SW_Check_In: Compile/Check In Capabilities and Settings
    SW_Check_In -[#blue]>  Build_System: Compile/Check In Capabilities and Settings
    RTE -[#blue]> Build_System : Compile/Check In Capabilities and Settings
    RTE -[#blue]> Build_System : Compile/Check In Capabilities and Settings
    SW_Check_In -[#blue]>  Verification_Validation: Verify and Validate System SW/Config.
    Verification_Validation -[#blue]>  Verification_Validation: MVP or Passes Use Cases

    RTE -[#red]>  TeamCenter: Released SW for HMI
    RTE -[#red]>  TeamCenter: Released SW for Main Control
    RTE -[#red]>  TeamCenter: Released Configurations for System
    RTE -[#red]>  TeamCenter: Released Capabilities for System
    note right
    **SW Release:** Used to Program through SWD.
    Programming completed with IDE Programmer and PC.
    Used by Supplier and Electrolux Factories to program 
    boards individually (Discretely).
    end note

    ==Discrete Subsystem SW Update-SWD Interface==
    HMI_SW_Engineer -[#blue]>  Discrete_Release_HMI: Release to TeamCenter
    note left
    **SW Release:** Subsystem definition is an HMI Assembly,
    Main Control Assembly, Auxiliary Assembly as defined by Horizon.
    end note
    MC_Assembly_SW_Engineer -[#blue]>  Discrete_Release_MC: Release to TeamCenter
    Configurations_Systems_Engineer-[#blue]>  Discrete_Release_Systems_Configurations: Release to TeamCenter

    ==System Bundle Release SW - Wireless Interface==
    Bundle_Descriptor_File -[#blue]> Bundle_System_SW
    Bundle_System_SW -[#blue]>  Discrete_Release_HMI: Release from TeamCenter
    Bundle_System_SW -[#blue]>  Discrete_Release_MC: Release from TeamCenter
    Bundle_System_SW -[#blue]>  Discrete_Release_Systems_Configurations: Release from TeamCenter
    Bundle_Encrypt -[#blue]>  Systems_SW_Update: Release to TeamCenter
@enduml