
//  Copyright (c) Electrolux Group. All rights reserved.
#ifndef __ORL_S00007697_A_KEYS_H
#define __ORL_S00007697_A_KEYS_H

#define orlKey_KEY_ConnectivityCommunicationProtocols_CommunicationProtocol1_protocol_defaultUserSetting                                              0x00000000
#define orlKey_KEY_Connectivity_communicationProtocolsKey                                                                                             0x00000080
#define orlKey_KEY_Connectivity_transmissionPowerReduction_configurationProfileVersion                                                                0x00000000
#define orlKey_KEY_OvenActivationTransition_conditionsKey                                                                                             0x00000000
#define orlKey_KEY_OvenActivationTransitions_activationTransitionKey1                                                                                 0x00000000
#define orlKey_KEY_OvenAttributes_attribute1                                                                                                          0x00000000
#define orlKey_KEY_OvenCavityCavityTemperatureSensors_cavityTemperatureSensorType                                                                     0x00000000
#define orlKey_KEY_OvenCavityCavityTemperatureSensors_doorUnlockTemperature                                                                           0x00000002
#define orlKey_KEY_OvenCavityCavityTemperatureSensors_maximumCurrentCookTemperature_maximumCurrentCleanTemperature                                    0x00000001
#define orlKey_KEY_OvenCavityCavityTemperatureSensors_openCircuitThreshold                                                                            0x00000004
#define orlKey_KEY_OvenCavityCavityTemperatureSensors_shortCircuitThreshold                                                                           0x00000003
#define orlKey_KEY_OvenCavityConvectionFan_speed1_level_powerRating                                                                                   0x00000000
#define orlKey_KEY_OvenCavityConvectionFans_convectionFansKey1                                                                                        0x00000000
#define orlKey_KEY_OvenCavityConvectionFans_ovenCavityConvectionFan_type                                                                              0x00000000
#define orlKey_KEY_OvenCavityConvectionFans_speedsKey                                                                                                 0x00000080
#define orlKey_KEY_OvenCavityCycledLoads_cycledLoad1_type_powerRating                                                                                 0x00000000
#define orlKey_KEY_OvenCavityFoodProbes_foodProbeType                                                                                                 0x00000000
#define orlKey_KEY_OvenCavityFoodProbes_maximumCurrentTemperature                                                                                     0x00000001
#define orlKey_KEY_OvenCavityFoodProbes_shortCircuitThreshold                                                                                         0x00000002
#define orlKey_KEY_OvenCavityOnOffLoads_onOffLoad1_type_powerRating                                                                                   0x00000000
#define orlKey_KEY_OvenCavitySwitches_switch1_type                                                                                                    0x00000000
#define orlKey_KEY_OvenCavity_cavityTemperatureSensorKey                                                                                              0x00000084
#define orlKey_KEY_OvenCavity_convectionFansKey                                                                                                       0x00000082
#define orlKey_KEY_OvenCavity_cycledLoadsKey                                                                                                          0x00000080
#define orlKey_KEY_OvenCavity_doorOpenTimeout_doorOpenResetCycleTime                                                                                  0x00000006
#define orlKey_KEY_OvenCavity_dutyPeriod_cycledLoadsMinimumOnTime_cycledLoadsMinimumOffTime                                                           0x00000001
#define orlKey_KEY_OvenCavity_foodProbeKey                                                                                                            0x00000085
#define orlKey_KEY_OvenCavity_maximumAllowedLoadPower                                                                                                 0x00000002
#define orlKey_KEY_OvenCavity_maximumAllowedTargetCookTime                                                                                            0x00000003
#define orlKey_KEY_OvenCavity_maximumAllowedTargetTemperatureNonPyrolyticClean_maximumAllowedTargetTemperaturePyrolyticClean                          0x00000005
#define orlKey_KEY_OvenCavity_maximumAllowedTargetTemperatureWithFoodProbePlugged                                                                     0x00000004
#define orlKey_KEY_OvenCavity_microwaveCookingTechnologyKey                                                                                           0x00000088
#define orlKey_KEY_OvenCavity_motorDoorLockKey                                                                                                        0x00000083
#define orlKey_KEY_OvenCavity_onOffLoadsKey                                                                                                           0x00000081
#define orlKey_KEY_OvenCavity_pollutionThreshold                                                                                                      0x00000007
#define orlKey_KEY_OvenCavity_steamCookingTechnologyKey                                                                                               0x00000087
#define orlKey_KEY_OvenCavity_switchKey                                                                                                               0x00000086
#define orlKey_KEY_OvenCavity_type                                                                                                                    0x00000000
#define orlKey_KEY_OvenCondition_leftOperand1_leftOperand2Availability_etc                                                                            0x00000000
#define orlKey_KEY_OvenCondition_rightOperandConstant                                                                                                 0x00000001
#define orlKey_KEY_OvenConditions_conditionKey1                                                                                                       0x00000000
#define orlKey_KEY_OvenConfiguration_connectivityKey                                                                                                  0x00000081
#define orlKey_KEY_OvenConfiguration_constructionsKey                                                                                                 0x00000085
#define orlKey_KEY_OvenConfiguration_cookTimePartialFinishTone_macsVersion_etc                                                                        0x00000004
#define orlKey_KEY_OvenConfiguration_coolingFansKey                                                                                                   0x00000084
#define orlKey_KEY_OvenConfiguration_defaultSetReminderTime                                                                                           0x00000007
#define orlKey_KEY_OvenConfiguration_energySavingShutOffTime                                                                                          0x00000001
#define orlKey_KEY_OvenConfiguration_expansionControllersKey                                                                                          0x00000083
#define orlKey_KEY_OvenConfiguration_idleLampOnTime                                                                                                   0x00000003
#define orlKey_KEY_OvenConfiguration_maximumSetReminderTime                                                                                           0x00000009
#define orlKey_KEY_OvenConfiguration_maximumSuggestedReminderTime                                                                                     0x00000008
#define orlKey_KEY_OvenConfiguration_minimumSetReminderTime                                                                                           0x00000005
#define orlKey_KEY_OvenConfiguration_minimumSuggestedReminderTime                                                                                     0x00000006
#define orlKey_KEY_OvenConfiguration_ovenProcessCompletedLampOnTime                                                                                   0x00000002
#define orlKey_KEY_OvenConfiguration_ovenProcessQueueKey                                                                                              0x00000087
#define orlKey_KEY_OvenConfiguration_ovenProcessesKey                                                                                                 0x00000086
#define orlKey_KEY_OvenConfiguration_powerControllersKey                                                                                              0x00000082
#define orlKey_KEY_OvenConfiguration_powerSupplySetUp_powerSupplyVoltage_powerSupplyFrequency_powerSupplyTimeSync                                     0x0000000B
#define orlKey_KEY_OvenConfiguration_stepSetReminderTime                                                                                              0x0000000A
#define orlKey_KEY_OvenConfiguration_taxonomyKey                                                                                                      0x00000080
#define orlKey_KEY_OvenConfiguration_type                                                                                                             0x00000000
#define orlKey_KEY_OvenConstruction_constructionDataKey                                                                                               0x00000080
#define orlKey_KEY_OvenConstruction_coolingFansSettingsKey                                                                                            0x00000081
#define orlKey_KEY_OvenConstruction_macsAddress                                                                                                       0x00000000
#define orlKey_KEY_OvenConstruction_minimumAllowedFoodProbeUserSetTemperature_maximumAllowedFoodProbeUserSetTemperature                               0x00000003
#define orlKey_KEY_OvenConstruction_minimumAllowedUserSetPower_maximumAllowedUserSetPower                                                             0x00000004
#define orlKey_KEY_OvenConstruction_minimumAllowedUserSetTemperature_maximumAllowedUserSetTemperature                                                 0x00000002
#define orlKey_KEY_OvenConstruction_position_default_phase                                                                                            0x00000001
#define orlKey_KEY_OvenConstructions_constructionKey1                                                                                                 0x00000000
#define orlKey_KEY_OvenCookOptions_cookoption1_Type_Default                                                                                           0x00000000
#define orlKey_KEY_OvenCookingMode_cookTimeMandatory_cookTimeStartAfterPreHeat_cookTimePartialFinishTone                                              0x00000001
#define orlKey_KEY_OvenCookingMode_cookingMode                                                                                                        0x00000000
#define orlKey_KEY_OvenCookingMode_defaultFoodProbeSetTemperature_stepFoodProbeSetTemperature                                                         0x00000004
#define orlKey_KEY_OvenCookingMode_defaultSetCookTime                                                                                                 0x00000004
#define orlKey_KEY_OvenCookingMode_defaultSetHumidity_stepSetHumidity                                                                                 0x00000004
#define orlKey_KEY_OvenCookingMode_defaultSetPower_stepSetPower                                                                                       0x00000004
#define orlKey_KEY_OvenCookingMode_defaultSetQuantity_stepSetQuantity                                                                                 0x00000004
#define orlKey_KEY_OvenCookingMode_defaultSetTemperature_stepSetTemperature                                                                           0x00000004
#define orlKey_KEY_OvenCookingMode_fakeRampTemperatureKey                                                                                             0x00000081
#define orlKey_KEY_OvenCookingMode_foodProbeMandatory_showFoodProbeSetTemperature_etc                                                                 0x00000001
#define orlKey_KEY_OvenCookingMode_humidityEstimationParametersKey                                                                                    0x00000081
#define orlKey_KEY_OvenCookingMode_maximumFoodProbeSetTemperature_maximumSuggestedFoodProbeSetTemperature                                             0x00000003
#define orlKey_KEY_OvenCookingMode_maximumSetCookTime                                                                                                 0x00000006
#define orlKey_KEY_OvenCookingMode_maximumSetHumidity_maximumSuggestedSetHumidity                                                                     0x00000003
#define orlKey_KEY_OvenCookingMode_maximumSetPower_maximumSuggestedSetPower                                                                           0x00000003
#define orlKey_KEY_OvenCookingMode_maximumSetQuantity_maximumSuggestedSetQuantity                                                                     0x00000003
#define orlKey_KEY_OvenCookingMode_maximumSetTemperature_maximumSuggestedSetTemperature                                                               0x00000003
#define orlKey_KEY_OvenCookingMode_maximumSuggestedSetCookTime                                                                                        0x00000005
#define orlKey_KEY_OvenCookingMode_measurementUnit                                                                                                    0x00000001
#define orlKey_KEY_OvenCookingMode_minimumFoodProbeSetTemperature_minimumSuggestedFoodProbeSetTemperature                                             0x00000002
#define orlKey_KEY_OvenCookingMode_minimumSetCookTime                                                                                                 0x00000002
#define orlKey_KEY_OvenCookingMode_minimumSetHumidity_minimumSuggestedSetHumidity                                                                     0x00000002
#define orlKey_KEY_OvenCookingMode_minimumSetPower_minimumSuggestedSetPower                                                                           0x00000002
#define orlKey_KEY_OvenCookingMode_minimumSetQuantity_minimumSuggestedSetQuantity                                                                     0x00000002
#define orlKey_KEY_OvenCookingMode_minimumSetTemperature_minimumSuggestedSetTemperature                                                               0x00000002
#define orlKey_KEY_OvenCookingMode_minimumSuggestedSetCookTime                                                                                        0x00000003
#define orlKey_KEY_OvenCookingMode_setHumidityLevelsKey                                                                                               0x00000080
#define orlKey_KEY_OvenCookingMode_setTemperatureLevelsKey                                                                                            0x00000080
#define orlKey_KEY_OvenCookingMode_showSetHumidity_showCurrentHumidity_humidityEstimation                                                             0x00000001
#define orlKey_KEY_OvenCookingMode_showSetPower                                                                                                       0x00000001
#define orlKey_KEY_OvenCookingMode_showSetTemperature_showCurrentTemperature_airCleanOffset                                                           0x00000001
#define orlKey_KEY_OvenCookingMode_stepSetCookTime                                                                                                    0x00000007
#define orlKey_KEY_OvenCookingModes_CookingMode_CookTime                                                                                              0x00000001
#define orlKey_KEY_OvenCookingModes_CookingMode_FoodProbe                                                                                             0x00000002
#define orlKey_KEY_OvenCookingModes_CookingMode_Humidity                                                                                              0x00000003
#define orlKey_KEY_OvenCookingModes_CookingMode_Microwave                                                                                             0x00000004
#define orlKey_KEY_OvenCookingModes_CookingMode_Quantity                                                                                              0x00000005
#define orlKey_KEY_OvenCookingModes_CookingMode_Temperature                                                                                           0x00000000
#define orlKey_KEY_OvenCoolingFanSetting_coolingFanIndex_coolingFanType_controlType                                                                   0x00000000
#define orlKey_KEY_OvenCoolingFanSetting_speedsKey                                                                                                    0x00000080
#define orlKey_KEY_OvenCoolingFanSettings_coolingFanSettingKey1                                                                                       0x00000000
#define orlKey_KEY_OvenCoolingFanSpeeds_coolingFanSpeed1_level_powerRating                                                                            0x00000000
#define orlKey_KEY_OvenCoolingFan_coolingFanDataKey                                                                                                   0x00000080
#define orlKey_KEY_OvenCoolingFan_macsAddress                                                                                                         0x00000000
#define orlKey_KEY_OvenCoolingFans_coolingFanKey1                                                                                                     0x00000000
#define orlKey_KEY_OvenCorrectionParameters_defaultSetCookTime                                                                                        0x00000003
#define orlKey_KEY_OvenCorrectionParameters_maximumSetCookTime                                                                                        0x00000005
#define orlKey_KEY_OvenCorrectionParameters_maximumSuggestedSetCookTime                                                                               0x00000004
#define orlKey_KEY_OvenCorrectionParameters_minimumSetCookTime                                                                                        0x00000001
#define orlKey_KEY_OvenCorrectionParameters_minimumSuggestedSetCookTime                                                                               0x00000002
#define orlKey_KEY_OvenCorrectionParameters_normalPreHeatOffset_fastPreHeatOffset_ecoPreHeatOffset_postHeatOffset                                     0x00000001
#define orlKey_KEY_OvenCorrectionParameters_stepSetCookTime                                                                                           0x00000006
#define orlKey_KEY_OvenCorrectionParameters_type                                                                                                      0x00000000
#define orlKey_KEY_OvenDeactivationTransition_conditionsKey                                                                                           0x00000080
#define orlKey_KEY_OvenDeactivationTransition_execution_nextMessageIndex                                                                              0x00000000
#define orlKey_KEY_OvenDeactivationTransition_nextOvenProcess                                                                                         0x00000001
#define orlKey_KEY_OvenDeactivationTransitions_deactivationTransitionKey1                                                                             0x00000000
#define orlKey_KEY_OvenGeneral_behavior                                                                                                               0x00000000
#define orlKey_KEY_OvenHumidityEstimation_estimationThreshold_slopeEstimationTimeVsThresholdTime_estimationTimeVsThresholdTime                        0x00000000
#define orlKey_KEY_OvenLoadParametersConvectionFansPhaseQueues_phaseKey1                                                                              0x00000000
#define orlKey_KEY_OvenLoadParametersConvectionFans_convectionFan1_type_speed                                                                         0x00000000
#define orlKey_KEY_OvenLoadParametersCoolingFans_coolingFan1_type_speed_postActivationSpeed_postActivationDelayOffDuration                            0x00000000
#define orlKey_KEY_OvenLoadParametersCycledLoads_cycledLoad1_type_start_end                                                                           0x00000000
#define orlKey_KEY_OvenLoadParametersOnOffLoads_onOffLoad1_type_status                                                                                0x00000000
#define orlKey_KEY_OvenLoadParameters_convectionFansAndCycledLoadsDutyPeriod_convectionFansAndLoadsLink_etc                                           0x00000000
#define orlKey_KEY_OvenLoadParameters_convectionFansPhaseQueueKey                                                                                     0x00000082
#define orlKey_KEY_OvenLoadParameters_coolingFansKey                                                                                                  0x00000083
#define orlKey_KEY_OvenLoadParameters_cycledLoadsKey                                                                                                  0x00000080
#define orlKey_KEY_OvenLoadParameters_onOffLoadsKey                                                                                                   0x00000081
#define orlKey_KEY_OvenMacsMessageVersions_macsMessageVersion1                                                                                        0x00000000
#define orlKey_KEY_OvenMessageQueue_messageKey1                                                                                                       0x00000080
#define orlKey_KEY_OvenMessageQueue_messageQueueIndex                                                                                                 0x00000000
#define orlKey_KEY_OvenMessage_activationTransitionsKey                                                                                               0x00000082
#define orlKey_KEY_OvenMessage_deactivationTransitionsKey                                                                                             0x00000083
#define orlKey_KEY_OvenMessage_generalKey                                                                                                             0x00000080
#define orlKey_KEY_OvenMessage_messageIndex                                                                                                           0x00000000
#define orlKey_KEY_OvenMessage_soundKey                                                                                                               0x00000081
#define orlKey_KEY_OvenPhaseQueueSelection_conditionsKey                                                                                              0x00000002
#define orlKey_KEY_OvenPhaseQueueSelection_correctionParametersKey                                                                                    0x00000001
#define orlKey_KEY_OvenPhaseQueueSelection_phaseQueueKey                                                                                              0x00000000
#define orlKey_KEY_OvenPhaseQueueSelections_phaseQueueSelectionKey1                                                                                   0x00000000
#define orlKey_KEY_OvenPhaseQueue_phaseKey1                                                                                                           0x00000000
#define orlKey_KEY_OvenPhase_convectionFansKey                                                                                                        0x00000080
#define orlKey_KEY_OvenPhase_duration                                                                                                                 0x00000000
#define orlKey_KEY_OvenPhase_loadParametersKey                                                                                                        0x00000080
#define orlKey_KEY_OvenPhase_messageQueueKey                                                                                                          0x00000083
#define orlKey_KEY_OvenPhase_phaseHumidityConstantValue_phasePowerConstantValue                                                                       0x00000004
#define orlKey_KEY_OvenPhase_phaseTemperatureConstantValue_phaseFoodProbeTemperatureConstantValue                                                     0x00000003
#define orlKey_KEY_OvenPhase_pollutionParametersKey                                                                                                   0x00000082
#define orlKey_KEY_OvenPhase_regulationParametersKey                                                                                                  0x00000081
#define orlKey_KEY_OvenPhase_subType_targetTemperatureLimitation_phaseTone_tankEmptyNotification                                                      0x00000001
#define orlKey_KEY_OvenPhase_transitionsKey                                                                                                           0x00000084
#define orlKey_KEY_OvenPhase_type                                                                                                                     0x00000000
#define orlKey_KEY_OvenPhase_userSetTemperatureFlag_userProgrammableOffsetFlag_bandOffsetFlag_etc                                                     0x00000002
#define orlKey_KEY_OvenPollutionParametersTable_temperatureRange_minimumTemperature_maximumTemperature                                                0x00000000
#define orlKey_KEY_OvenPollutionParametersTable_temperatureRange_slope_offset                                                                         0x00000001
#define orlKey_KEY_OvenPollutionParameters_temperatureRangeKey1                                                                                       0x00000000
#define orlKey_KEY_OvenPowerController_macsAddress                                                                                                    0x00000000
#define orlKey_KEY_OvenPowerController_macsMessageVersionsKey                                                                                         0x00000080
#define orlKey_KEY_OvenPowerController_preBuiltByteArrayClassA                                                                                        0x00000081
#define orlKey_KEY_OvenPowerController_preBuiltByteArrayClassB                                                                                        0x00000082
#define orlKey_KEY_OvenPowerControllers_powerControllerKey1                                                                                           0x00000000
#define orlKey_KEY_OvenProcess_attributesKey                                                                                                          0x00000081
#define orlKey_KEY_OvenProcess_auxiliaryMessageQueueKey                                                                                               0x00000083
#define orlKey_KEY_OvenProcess_cookOptionsKey                                                                                                         0x00000080
#define orlKey_KEY_OvenProcess_cookingModesKey                                                                                                        0x00000084
#define orlKey_KEY_OvenProcess_mainMessageQueueKey                                                                                                    0x00000082
#define orlKey_KEY_OvenProcess_maximumAllowedUserSetDelayStart                                                                                        0x00000001
#define orlKey_KEY_OvenProcess_phaseQueueSelectionsKey                                                                                                0x00000085
#define orlKey_KEY_OvenProcess_type                                                                                                                   0x00000000
#define orlKey_KEY_OvenProcesses_FactoryTest_Cav1CookFan                                                                                              0x1A3F1FAE
#define orlKey_KEY_OvenProcesses_Program_BakeNefario                                                                                                  0x90876609
#define orlKey_KEY_OvenProcesses_Program_BottomGrill                                                                                                  0x82BF4D41
#define orlKey_KEY_OvenProcesses_Program_BottomTrueFan                                                                                                0xCDCEB5FC
#define orlKey_KEY_OvenProcesses_Program_FullPureMicrowave                                                                                            0xBCB6EA69
#define orlKey_KEY_OvenProcesses_Program_FullSteam_PS1_                                                                                               0x091CFE36
#define orlKey_KEY_OvenProcesses_Program_Grill                                                                                                        0x0A9ADA27
#define orlKey_KEY_OvenProcesses_Program_GrillFan                                                                                                     0x0BB53979
#define orlKey_KEY_OvenProcesses_Program_HighSteam_PS1_                                                                                               0x2D71631B
#define orlKey_KEY_OvenProcesses_Program_LowSteam_PS1_                                                                                                0x5062FE69
#define orlKey_KEY_OvenProcesses_Program_MediumSteam_PS1_                                                                                             0x0EE314C1
#define orlKey_KEY_OvenProcesses_Program_Sample                                                                                                       0x6F833577
#define orlKey_KEY_OvenProcesses_Program_SousVide_PS1_                                                                                                0x91E72537
#define orlKey_KEY_OvenProcesses_Program_Steamify_PS1_                                                                                                0x2E2F741D
#define orlKey_KEY_OvenProcesses_Program_TrueFan                                                                                                      0x9002F71F
#define orlKey_KEY_OvenProcesses_Program_Turkey                                                                                                       0x3A2CD8D3
#define orlKey_KEY_OvenProcesses_SteamClean_Light_PS1_                                                                                                0x76869017
#define orlKey_KEY_OvenRegulationParameters_afterBoostOvershootDecrement_incessantFirstHeatUntilSetPoint                                              0x00000006
#define orlKey_KEY_OvenRegulationParameters_boostTemperatureThreshold                                                                                 0x00000003
#define orlKey_KEY_OvenRegulationParameters_curve1Slope_curve1Intercept_curve2Slope_curve2Intercept                                                   0x00000002
#define orlKey_KEY_OvenRegulationParameters_derivativeFilterCoefficient_derivativeUpperOffset_derivativeLowerOffset                                   0x00000004
#define orlKey_KEY_OvenRegulationParameters_divisor_clearIntegral                                                                                     0x00000005
#define orlKey_KEY_OvenRegulationParameters_executionRate                                                                                             0x00000001
#define orlKey_KEY_OvenRegulationParameters_forcedOvershootValue_forcedOvershootDecrement_heatingPulseDurationBy30C_heatingPulseDurationBy300C        0x00000005
#define orlKey_KEY_OvenRegulationParameters_kw_kp                                                                                                     0x00000002
#define orlKey_KEY_OvenRegulationParameters_modelParametersDelay_modelParametersMaxTemperature_modelParametersMinTemperature                          0x00000004
#define orlKey_KEY_OvenRegulationParameters_modelParametersR_modelParametersL                                                                         0x00000003
#define orlKey_KEY_OvenRegulationParameters_overshootFactor_overshootCounter_regulationAreaOffset_regulationAreaPower_hysteresis                      0x00000003
#define orlKey_KEY_OvenRegulationParameters_temperatureThresholdBetweenCurves                                                                         0x00000001
#define orlKey_KEY_OvenRegulationParameters_ti_td                                                                                                     0x00000003
#define orlKey_KEY_OvenRegulationParameters_type                                                                                                      0x00000000
#define orlKey_KEY_OvenRegulationParameters_upperTemperatureDelta_lowerTemperatureDelta                                                               0x00000002
#define orlKey_KEY_OvenShowCurrentTemperature_fakePreHeatThresholdReached_fakeRampRate                                                                0x00000000
#define orlKey_KEY_OvenShowSetTemperatureLevel_setTemperatureLevel1                                                                                   0x00000000
#define orlKey_KEY_OvenSound_soundSequence_soundMode_soundPeriod                                                                                      0x00000000
#define orlKey_KEY_OvenSpeed_activationTemperatureOrTimeThreshold_deactivationTemperatureOrTimeThreshold                                              0x00000001
#define orlKey_KEY_OvenSpeed_level                                                                                                                    0x00000000
#define orlKey_KEY_OvenSpeeds_speedKey1                                                                                                               0x00000000
#define orlKey_KEY_OvenSteamTechnologyConversionColumn_humiditylevel1_humidityThreshold_estimatedHumidity                                             0x00000000
#define orlKey_KEY_OvenSteamTechnologyConversionColumns_humidityLevelsKey                                                                             0x00000080
#define orlKey_KEY_OvenSteamTechnologyConversionColumns_minimumTemperature_maximumTemperature                                                         0x00000000
#define orlKey_KEY_OvenSteamTechnologyConversionTables_conversionColumnsKey1                                                                          0x00000000
#define orlKey_KEY_OvenSteamTechnologyCycledLoads_cycledLoad1_type_powerRating                                                                        0x00000000
#define orlKey_KEY_OvenSteamTechnologyDescaling_thresholdKey1                                                                                         0x00000000
#define orlKey_KEY_OvenSteamTechnologyHumidityRestrictions_maximumAllowedHumidity                                                                     0x00000000
#define orlKey_KEY_OvenSteamTechnologyHumiditySensors_conversionSlope_conversionOffset                                                                0x00000002
#define orlKey_KEY_OvenSteamTechnologyHumiditySensors_conversionTableKey                                                                              0x00000080
#define orlKey_KEY_OvenSteamTechnologyHumiditySensors_humiditySensorType                                                                              0x00000000
#define orlKey_KEY_OvenSteamTechnologyHumiditySensors_shortCircuitThreshold_openCircuitThreshold                                                      0x00000001
#define orlKey_KEY_OvenSteamTechnologyOnOffLoads_onOffLoad1_type_powerRating                                                                          0x00000000
#define orlKey_KEY_OvenSteamTechnologyTank_WaterInletValve_initialOpeningTime_openingTime_waitingTime_temperatureThreshold                            0x00000000
#define orlKey_KEY_OvenSteamTechnologyTank_tankSwitchType                                                                                             0x00000000
#define orlKey_KEY_OvenSteamTechnologyTank_waterLevelSensorType                                                                                       0x00000000
#define orlKey_KEY_OvenSteamTechnologyTanks_debounceMinimumTime_debounceMaximumTime                                                                   0x00000001
#define orlKey_KEY_OvenSteamTechnologyTanks_tankParametersKey                                                                                         0x00000080
#define orlKey_KEY_OvenSteamTechnologyTanks_tankSwitchesKey                                                                                           0x00000082
#define orlKey_KEY_OvenSteamTechnologyTanks_tankType                                                                                                  0x00000000
#define orlKey_KEY_OvenSteamTechnologyTanks_waterLevelSensorsKey                                                                                      0x00000081
#define orlKey_KEY_OvenSteamTechnologyTemperatureRestrictions_cavityTemperatureThreshold                                                              0x00000000
#define orlKey_KEY_OvenSteamTechnologyTemperatureSensors_temperatureSensorType                                                                        0x00000000
#define orlKey_KEY_OvenSteamTechnologyThreshold_blockingThreshold                                                                                     0x00000002
#define orlKey_KEY_OvenSteamTechnologyThreshold_nonBlockingThreshold                                                                                  0x00000001
#define orlKey_KEY_OvenSteamTechnologyThreshold_waterHardness                                                                                         0x00000000
#define orlKey_KEY_OvenSteamTechnology_cookingTechnologyType                                                                                          0x00000000
#define orlKey_KEY_OvenSteamTechnology_cycledLoadsKey                                                                                                 0x00000082
#define orlKey_KEY_OvenSteamTechnology_descalingKey                                                                                                   0x00000087
#define orlKey_KEY_OvenSteamTechnology_humidityRestrictionsKey                                                                                        0x00000080
#define orlKey_KEY_OvenSteamTechnology_humiditySensorKey                                                                                              0x00000084
#define orlKey_KEY_OvenSteamTechnology_onOffLoadsKey                                                                                                  0x00000083
#define orlKey_KEY_OvenSteamTechnology_tankKey                                                                                                        0x00000086
#define orlKey_KEY_OvenSteamTechnology_temperatureRestrictionsKey                                                                                     0x00000081
#define orlKey_KEY_OvenSteamTechnology_temperatureSensorKey                                                                                           0x00000085
#define orlKey_KEY_OvenTransition_conditionsKey                                                                                                       0x00000080
#define orlKey_KEY_OvenTransition_nextPhaseIndex                                                                                                      0x00000000
#define orlKey_KEY_OvenTransitions_transitionKey1                                                                                                     0x00000000
#define orlKey_KEY_Oven_speedsKey                                                                                                                     0x00000080
#define orlKey_KEY_Oven_tachometerKey                                                                                                                 0x00000081
#define orlKey_KEY_Oven_type                                                                                                                          0x00000000
#define orlKey_KEY_TaxonomyElementOptions_default                                                                                                     0x00000002
#define orlKey_KEY_TaxonomyElementOptions_name                                                                                                        0x00000001
#define orlKey_KEY_TaxonomyElementOptions_optionsKey                                                                                                  0x00000080
#define orlKey_KEY_TaxonomyElementOptions_type                                                                                                        0x00000000
#define orlKey_KEY_TaxonomyElements_elementKey1                                                                                                       0x00000000
#define orlKey_KEY_TaxonomyOptions_option1                                                                                                            0x00000000
#define orlKey_KEY_Taxonomy_elementsKey                                                                                                               0x00000080
#define orlKey_KEY_Taxonomy_type                                                                                                                      0x00000000

#endif // __ORL_S00007697_A_KEYS_H
