@startuml Configuration_Process


    autonumber
    actor Configuration_Architect
    actor Configuration_Engineer

    ==Configuration Data Structure==

    Configuration_Architect -[#red]> Config_Tool : Update Data Structure
    note left 
    **Role and Accountability**
    Maintains the data structure of the configuration file
    to ensure it accounts for all configuration parameters 
    within the Tech Stack of the Platform for a specific 
    Product Portfolio. (ex. Cooking = Freestanding Oven, 
    Induction Hobs, Radiant Hobs, Gas Hobs,Built In Ovens, 
    Hoods, Microwaves).  This includes Product and Connectivity
    Configuration Parameters.
    end note

    Config_Tool -[#red]> Product_Config : Update Data Structure
    Config_Tool -[#red]> Connectivity_Config : Update Data Structure
    Config_Tool -[#red]> Product_Config: Export Product Config UI
    Config_Tool -[#red]> Product_Config: Export Product Config GPU
    Config_Tool -[#red]> Product_Config: Export Product Config Touch
    Config_Tool -[#red]> Product_Config: Export Product Config Graphical Assets
    Config_Tool -[#red]> Product_Config: Export Product Config Main Control
    Config_Tool -[#red]> Product_Config: Export Product Config Auxliary Control
    Config_Tool -[#red]> Connectivity_Config: Export Connectivity Config Capabilities
    Config_Tool -[#red]> Connectivity_Config: Export Connectivity Config States
    Configuration_Architect -[#Green]> Config_Tool: Verify Data Structure for all exports
    note right
    **Role and Accountability**
    Verify the Data Archicture is aligned with Category Configuration
    Engineers, Software Category Engineers, Connectivity Engineers for 
    Data Entry.
    end note

    ==Configuration Editing==

    Configuration_Engineer -[#red]> Config_Tool : Open Tool on PC
    note left
    **Role and Accountability**
    Edit the unique PNC Appliance Configuration Data Structure, adding the specific
    parametric data for the Product and Connectivity for a specific instance
    of a PNC Appliance Release.
    end note
    Configuration_Engineer -[#red]> Config_Tool : Edit Category Specific Configuration File
    Configuration_Engineer -[#red]> Config_Tool : Enter all data for Product
    Configuration_Engineer -[#red]> Config_Tool : Enter all data for Connectivity

    ==Configurations Release==

    Configuration_Engineer -[#red]> Config_Tool : Start Export Process Once All Data Is Entered
    Config_Tool -[#Green]> Product_Config: Export Configuration Files
    Product_Config -[#red]> Product_Config: Export Product Config UI
    Product_Config -[#red]> Product_Config: Export Product Config GPU
    Product_Config -[#red]> Product_Config: Export Product Config Touch
    Product_Config -[#red]> Product_Config: Export Product Config Graphical Assets
    Product_Config -[#red]> Product_Config: Export Product Config Main Control
    Product_Config -[#red]> Product_Config: Export Product Config Auxiliary Control
    Product_Config -[#green]> Config_Tool: Export Product Configurations and Formats for Product
    Connectivity_Config -[#red]> Connectivity_Config: Export Connectivity Config Capabilities
    Connectivity_Config -[#red]> Connectivity_Config: Export Connectivity Config States
    Connectivity_Config -[#green]> Config_Tool: Export Connectivity Configurations and Formats for Connectivity
    Config_Tool -[#red]> Config_Tool: Bundle all files into File System
    Config_Tool -[#Green]> Configuration_Engineer: Folder from Configuration Tool Export "Ready"
    Configuration_Engineer -[#Green]> Release_Management_System: Release Main Folder and all Files into Production Release Process ECN/ECR
    
    ==Configuration Deployment==

   Configuration_Engineer -[#blue]> Product_Config: Software Update based on Scheduler
    note left 
    **Roles and Accountability:**

    end note
    
@enduml
